services:
  mood-db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - PGUSER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./init-dev-databases.sh:/docker-entrypoint-initdb.d/init-dev-databases.sh
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 2s
      timeout: 2s
      retries: 15

  mood-rs:
    build:
      context: services/backend/mood-rs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:pass@mood-db:5432
    depends_on:
      mood-db:
       condition: service_healthy
    develop:
      watch:
        - action: sync
          path: services/backend/mood-rs
          target: /app

  frontend-dev:
    build:
      context: services/frontend/demdemfront
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    develop:
      watch:
        - action: sync
          path: services/frontend/demdemfront
          target: /app
