FROM sbtscala/scala-sbt:eclipse-temurin-25.0.1_8_1.12.0_3.8.1 AS builder

WORKDIR /app
COPY .mill-version .
COPY mill .
COPY build.mill .
RUN ./mill --version

COPY app app
CMD ["./mill", "--notify-watch", "false", "--no-daemon", "-w", "app.api.runBackground"]